package com.example.taskmanagerapi.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "tasks")
public class Task {

    @Id
    private String id; // Will be automatically generated by MongoDB as ObjectId

    private String title;
    private String description;
    private String status; // e.g., "TO_DO", "IN_PROGRESS", "DONE"
    private LocalDateTime createdAt;

    // Custom logic for createdAt can be handled in the service layer before saving
    // or using @PrePersist if using JPA, but for Spring Data MongoDB,
    // manual setting in service or a lifecycle event listener is common.
    // For simplicity, we'll set it in the service layer.
}
